create table if not exists public.spans (
  trace_id text not null,
  span_id text not null,
  parent_span_id text,
  name text not null,
  operation varchar(64),
  provider varchar(128),
  agent_name text,
  model text,
  tool_name text,
  status varchar(16) not null,
  error_type text,
  start_time timestamptz not null,
  end_time timestamptz,
  input_tokens integer,
  output_tokens integer,
  cost_usd numeric(12, 6),
  attributes jsonb not null,
  resource_attributes jsonb not null,
  events jsonb not null,
  primary key (trace_id, span_id)
);

create index if not exists ix_spans_trace_started
  on public.spans (trace_id, start_time);

create index if not exists ix_spans_operation_started
  on public.spans (operation, start_time);

create table if not exists public.runs (
  trace_id text primary key,
  root_name text not null,
  status varchar(16) not null,
  started_at timestamptz not null,
  duration_ms integer,
  total_tokens integer not null default 0,
  cost_usd numeric(12, 6),
  prompt_hash text,
  model text,
  git_sha text,
  eval_run_id text,
  verdict varchar(16)
);

create table if not exists public.detections (
  id integer generated by default as identity primary key,
  trace_id text not null,
  span_id text,
  kind varchar(64) not null,
  severity varchar(16) not null,
  detail jsonb not null,
  created_at timestamptz not null
);

